### ISSUE TITLE
Better fitting model 

### ISSUE THREAD

**Issue by Rishabkashyap14** [shreya1010svg/census_data#2]
Find a model that can fit the dataset better

**Comment by abhishek-mishra17** [comment]
@shreya1010svg  @Rishabkashyap14  I would like to this

**Comment by abhishek-mishra17** [comment]
the dataset imported and the code written in the file does not match

**Comment by shreya1010svg** [comment]
I think it does. The code belongs to that dataset.

**Comment by Rishabkashyap14** [comment]
Hey @abhishek-pes, I too can confirm that the dataset matches with the code written

**Comment by abhishek-mishra17** [comment]
@Rishabkashyap14  @shreya1010svg 
![image](https://user-images.githubusercontent.com/54106076/97109906-023c2d80-16fc-11eb-8c55-3756755d9e7d.png)
like what i meant was these columns are not even present in the data set

**Comment by shreya1010svg** [comment]
@abhishek-pes now I get what you mean. The column titles are not in the csv. It's horrible I know, but for some reason this is how we got the dataset. You can modify it to include the column titles. The information is given in data_desciption.txt. Sorry for the trouble caused by the missing headings

**Comment by abhishek-mishra17** [comment]
Ahh no problem .. I'll try it out then

**Comment by shreya1010svg** [comment]
Please do
